on:
 workflow_dispatch:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Genereate a list of dependencies for this repository
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate dependencies action
      uses: ./ # Uses an action in the root directory
      id: deps    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.deps.outputs.repo }}"
