# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Build and Source Release

on:
 workflow_dispatch:
    branches:
      - main
    inputs:
      version_type:
        description: 'Version Bump Type (M)ajor, (m)inor, (p)atch'
        required: true
        default: 'p'
    
jobs:
  Create release and publish Docker image:
    
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: ['14']

    steps:
    - 
      uses: actions/checkout@v2

    - 
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - 
      name: Set ENV from VERSION
      run:  source VERSION


    - name: Display input parameters
      run: |
        echo version_type: $VERSION

    - name: Simple Semver
      id: semver
      uses: matt-FFFFFF/simple-semver@v0.1.0
      with:
        semver-input: ${{ env.VERSION }}
        increment: p

    - name: New version is ${{ steps.semver.outputs.semver }}
      run: echo ${{ steps.semver.outputs.semver }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
    
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/f1tv-dl-docker:latest
          ghcr.io/${{ github.repository_owner }}/f1tv-dl-docker:${{ steps.semver.outputs.semver }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.semver }}
        release_name: fltv-dl ${{ steps.semver.outputs.semver }}
        draft: false
        prerelease: false

    - 
      name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: the Dave
        author_email: dave@digitalnoise.net
        message: "Bump release version in VERSION file to ${{ steps.semver.outputs.semver }}"
        cwd: ${{ env.PROJECT_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}