# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Build

on:
  release:
    branches:
      - main
    types: 
      - released
    
      
jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - 
      uses: actions/checkout@v2

    - 
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    -
      run: |
        npm ci

    - 
      name: Generic Version Bumpr
      id: semver
      uses: PackagrIO/action-bumpr-generic@v0.0.1
      with:
        version_bump_type: minor
        version_metadata_path: VERSION

    - 
      run: echo version is ${{ steps.semver.outputs.release_version }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/f1tv-dl-docker:latest
          ghcr.io/${{ github.repository_owner }}/f1tv-dl-docker:${{ steps.semver.outputs.release_version }}

    - 
      name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: the Dave
        author_email: dave@digitalnoise.net
        message: "Bump release version in VERSION file to ${{ steps.semver.outputs.release_version }}"
        tag: ${{steps.bump_version.outputs.release_version}}
        cwd: ${{ env.PROJECT_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
