# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate build

on:  
  push:    
    paths-ignore:
      - '.github/**'
      - '**.md'
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:
  build:
    
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
    - 
      uses: actions/checkout@v2

    - 
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    -
      run: |
        ssh -vT git@github.com
        npm ci
        npm test