# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Versioning Workflow

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version Bump Type (m)ajor, m(i)nor, (p)atch"
        required: true
        default: "p"

jobs:
  test-versioning:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Read package.json
        id: read-package-json
        run: |
          content=`cat ./package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=package-json::$content"

      - name: Output version
        run: |
          echo "${{fromJson(steps.read-package-json.outputs.package-json).version}}"
